export const dummyJobPosts = [
  {
    id: "JID0001",
    title: "Senior mobile app developer",
    company: "Kepler Inc.",
    applicants: 5,
    postDate: "14 Jun 2022",
    status: "Active",
  },
  {
    id: "JID0002",
    title: "Product and UI/UX designer",
    company: "Kepler Inc.",
    applicants: 11,
    postDate: "14 Jun 2022",
    status: "Inactive",
  },
  {
    id: "JID0003",
    title: "Backend developer using FastAPI",
    company: "Flying Co.",
    applicants: 2,
    postDate: "14 Jun 2022",
    status: "Active",
  },
  {
    id: "JID0004",
    title: "Software Engineer I",
    company: "Kepler Inc.",
    applicants: 7,
    postDate: "14 Jun 2022",
    status: "Inactive",
  },
  {
    id: "JID0005",
    title: "Full-Stack web developer",
    company: "Flying Co.",
    applicants: 17,
    postDate: "14 Jun 2022",
    status: "Active",
  },
  {
    id: "JID0006",
    title: "Software quality assurance analyst",
    company: "Kepler Inc.",
    applicants: 0,
    postDate: "14 Jun 2022",
    status: "Inactive",
  },
  {
    id: "JID0007",
    title: "UI developer",
    company: "Flying Co.",
    applicants: 21,
    postDate: "14 Jun 2022",
    status: "Active",
  },
  {
    id: "JID0008",
    title: "Data Scientist",
    company: "Tech Solutions Ltd.",
    applicants: 3,
    postDate: "15 Jul 2022",
    status: "Active",
  },
  {
    id: "JID0009",
    title: "DevOps Engineer",
    company: "Cloudify Inc.",
    applicants: 10,
    postDate: "16 Jul 2022",
    status: "Active",
  },
  {
    id: "JID0010",
    title: "Cybersecurity Analyst",
    company: "SecureTech Ltd.",
    applicants: 4,
    postDate: "17 Jul 2022",
    status: "Inactive",
  },
  {
    id: "JID0011",
    title: "Systems Administrator",
    company: "Network Solutions Inc.",
    applicants: 8,
    postDate: "18 Jul 2022",
    status: "Active",
  },
  {
    id: "JID0012",
    title: "Project Manager",
    company: "Global Projects LLC",
    applicants: 12,
    postDate: "19 Jul 2022",
    status: "Active",
  },
  {
    id: "JID0013",
    title: "Technical Writer",
    company: "WriteItRight Inc.",
    applicants: 2,
    postDate: "20 Jul 2022",
    status: "Inactive",
  },
  {
    id: "JID0014",
    title: "Machine Learning Engineer",
    company: "IntelliTech Corp.",
    applicants: 6,
    postDate: "21 Jul 2022",
    status: "Active",
  },
  {
    id: "JID0015",
    title: "Cloud Solutions Architect",
    company: "SkyNet Services",
    applicants: 5,
    postDate: "22 Jul 2022",
    status: "Active",
  },
  {
    id: "JID0016",
    title: "Content Strategist",
    company: "Creative Minds Agency",
    applicants: 1,
    postDate: "23 Jul 2022",
    status: "Inactive",
  },
  {
    id: "JID0017",
    title: "Database Administrator",
    company: "DataCorp Solutions",
    applicants: 15,
    postDate: "24 Jul 2022",
    status: "Active",
  },
  {
    id: "JID0018",
    title: "Frontend Developer",
    company: "Tech Innovators",
    applicants: 20,
    postDate: "25 Jul 2022",
    status: "Active",
  },
  {
    id: "JID0019",
    title: "Business Analyst",
    company: "Visionary Analytics",
    applicants: 9,
    postDate: "26 Jul 2022",
    status: "Active",
  },
  {
    id: "JID0020",
    title: "SEO Specialist",
    company: "Digital Growth LLC",
    applicants: 3,
    postDate: "27 Jul 2022",
    status: "Inactive",
  },
  {
    id: "JID0021",
    title: "Marketing Manager",
    company: "Marketing Wizards",
    applicants: 10,
    postDate: "28 Jul 2022",
    status: "Active",
  },
  {
    id: "JID0022",
    title: "Cloud Engineer",
    company: "Cloud Solutions Group",
    applicants: 12,
    postDate: "29 Jul 2022",
    status: "Active",
  },
  {
    id: "JID0023",
    title: "Game Developer",
    company: "Epic Games",
    applicants: 8,
    postDate: "30 Jul 2022",
    status: "Inactive",
  },
  {
    id: "JID0024",
    title: "Application Support Analyst",
    company: "Services Inc.",
    applicants: 4,
    postDate: "31 Jul 2022",
    status: "Active",
  },
  {
    id: "JID0025",
    title: "Network Engineer",
    company: "Tech Connections",
    applicants: 7,
    postDate: "1 Aug 2022",
    status: "Inactive",
  },
  {
    id: "JID0026",
    title: "Research Scientist",
    company: "Bio Medics Corp.",
    applicants: 2,
    postDate: "2 Aug 2022",
    status: "Active",
  },
  {
    id: "JID0027",
    title: "Mobile UI/UX Designer",
    company: "Pixel Perfect",
    applicants: 5,
    postDate: "3 Aug 2022",
    status: "Active",
  },
  {
    id: "JID0028",
    title: "Network Security Specialist",
    company: "Secure Networks",
    applicants: 6,
    postDate: "4 Aug 2022",
    status: "Inactive",
  },
  {
    id: "JID0029",
    title: "Cloud Security Engineer",
    company: "CyberSolutions",
    applicants: 3,
    postDate: "5 Aug 2022",
    status: "Active",
  },
  {
    id: "JID0030",
    title: "User Experience Researcher",
    company: "Insightful UX",
    applicants: 1,
    postDate: "6 Aug 2022",
    status: "Inactive",
  },
  {
    id: "JID0031",
    title: "Blockchain Developer",
    company: "Future Tech",
    applicants: 4,
    postDate: "7 Aug 2022",
    status: "Active",
  },
  {
    id: "JID0032",
    title: "E-commerce Specialist",
    company: "Shopping Solutions",
    applicants: 9,
    postDate: "8 Aug 2022",
    status: "Active",
  },
  {
    id: "JID0033",
    title: "Graphic Designer",
    company: "Creative Agency",
    applicants: 14,
    postDate: "9 Aug 2022",
    status: "Inactive",
  },
  {
    id: "JID0034",
    title: "Hardware Engineer",
    company: "Tech Wizardry",
    applicants: 10,
    postDate: "10 Aug 2022",
    status: "Active",
  },
  {
    id: "JID0035",
    title: "Technical Account Manager",
    company: "ServiceFirst",
    applicants: 2,
    postDate: "11 Aug 2022",
    status: "Inactive",
  },
  {
    id: "JID0036",
    title: "Sales Engineer",
    company: "SalesPro Inc.",
    applicants: 15,
    postDate: "12 Aug 2022",
    status: "Active",
  },
  {
    id: "JID0037",
    title: "IT Support Technician",
    company: "TechAssist Corp.",
    applicants: 5,
    postDate: "13 Aug 2022",
    status: "Inactive",
  },
  {
    id: "JID0038",
    title: "Database Developer",
    company: "DataMasters LLC",
    applicants: 7,
    postDate: "14 Aug 2022",
    status: "Active",
  },
  {
    id: "JID0039",
    title: "Virtual Reality Developer",
    company: "VR Innovations",
    applicants: 6,
    postDate: "15 Aug 2022",
    status: "Active",
  },
  {
    id: "JID0040",
    title: "Data Engineer",
    company: "Data Pipeline Inc.",
    applicants: 4,
    postDate: "16 Aug 2022",
    status: "Inactive",
  },
  {
    id: "JID0041",
    title: "IT Project Manager",
    company: "Managed Solutions",
    applicants: 11,
    postDate: "17 Aug 2022",
    status: "Active",
  },
  {
    id: "JID0042",
    title: "Video Game Tester",
    company: "Playtesters Ltd.",
    applicants: 3,
    postDate: "18 Aug 2022",
    status: "Inactive",
  },
  {
    id: "JID0043",
    title: "Web Content Manager",
    company: "Content Corp.",
    applicants: 5,
    postDate: "19 Aug 2022",
    status: "Active",
  },
  {
    id: "JID0044",
    title: "Business Development Manager",
    company: "Growth Partners",
    applicants: 2,
    postDate: "20 Aug 2022",
    status: "Inactive",
  },
  {
    id: "JID0045",
    title: "Artificial Intelligence Engineer",
    company: "AI Solutions",
    applicants: 8,
    postDate: "21 Aug 2022",
    status: "Active",
  },
  {
    id: "JID0046",
    title: "Frontend React Developer",
    company: "Reactive Tech",
    applicants: 10,
    postDate: "22 Aug 2022",
    status: "Inactive",
  },
  {
    id: "JID0047",
    title: "Backend Node.js Developer",
    company: "NodeForce",
    applicants: 7,
    postDate: "23 Aug 2022",
    status: "Active",
  },
  {
    id: "JID0048",
    title: "IT Compliance Analyst",
    company: "Compliant Tech",
    applicants: 4,
    postDate: "24 Aug 2022",
    status: "Inactive",
  },
  {
    id: "JID0049",
    title: "Creative Director",
    company: "Creative Minds Group",
    applicants: 5,
    postDate: "25 Aug 2022",
    status: "Active",
  },
  {
    id: "JID0050",
    title: "User Interface Designer",
    company: "Design Duo",
    applicants: 3,
    postDate: "26 Aug 2022",
    status: "Inactive",
  },
  {
    id: "JID0051",
    title: "Augmented Reality Developer",
    company: "AR Studios",
    applicants: 6,
    postDate: "27 Aug 2022",
    status: "Active",
  },
  {
    id: "JID0052",
    title: "Email Marketing Specialist",
    company: "Reach Out Inc.",
    applicants: 9,
    postDate: "28 Aug 2022",
    status: "Active",
  },
  {
    id: "JID0053",
    title: "Corporate Trainer",
    company: "Learning Corp.",
    applicants: 4,
    postDate: "29 Aug 2022",
    status: "Inactive",
  },
  {
    id: "JID0054",
    title: "IT Operations Manager",
    company: "OpTech",
    applicants: 2,
    postDate: "30 Aug 2022",
    status: "Active",
  },
  {
    id: "JID0055",
    title: "SAP Consultant",
    company: "Enterprise Solutions",
    applicants: 10,
    postDate: "31 Aug 2022",
    status: "Inactive",
  },
  {
    id: "JID0056",
    title: "Data Analyst",
    company: "Analytics Pro",
    applicants: 5,
    postDate: "1 Sep 2022",
    status: "Active",
  },
  {
    id: "JID0057",
    title: "Documentation Specialist",
    company: "DocuWise Inc.",
    applicants: 1,
    postDate: "2 Sep 2022",
    status: "Inactive",
  },
  {
    id: "JID0058",
    title: "Help Desk Associate",
    company: "Support Experts",
    applicants: 3,
    postDate: "3 Sep 2022",
    status: "Active",
  },
  {
    id: "JID0059",
    title: "Quality Control Engineer",
    company: "AssureTech",
    applicants: 6,
    postDate: "4 Sep 2022",
    status: "Active",
  },
  {
    id: "JID0060",
    title: "Health Informatics Specialist",
    company: "HealthCorp",
    applicants: 2,
    postDate: "5 Sep 2022",
    status: "Inactive",
  },
  {
    id: "JID0061",
    title: "Pharmaceutical Sales Representative",
    company: "PharmaSales Inc.",
    applicants: 5,
    postDate: "6 Sep 2022",
    status: "Active",
  },
  {
    id: "JID0062",
    title: "Compliance Officer",
    company: "Regulatory Group",
    applicants: 8,
    postDate: "7 Sep 2022",
    status: "Inactive",
  },
  {
    id: "JID0063",
    title: "Supply Chain Analyst",
    company: "Logistics Leaders",
    applicants: 7,
    postDate: "8 Sep 2022",
    status: "Active",
  },
  {
    id: "JID0064",
    title: "Retail Merchandiser",
    company: "Retail Solutions",
    applicants: 4,
    postDate: "9 Sep 2022",
    status: "Inactive",
  },
  {
    id: "JID0065",
    title: "Interior Designer",
    company: "Design Space",
    applicants: 3,
    postDate: "10 Sep 2022",
    status: "Active",
  },
];
